### PR TITLE
Allow custom notification values

### PR DESCRIPTION
**Pull request by vmitchell85**
This will allow the addition of a `routeNotificationForSpark` onto any `Notifiable`.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can you use the `if` formatting used throughout the rest of the Laravel ecosystem?

**Comment by vmitchell85** [comment]
@taylorotwell Sorry about that, still new to contributing. I assume the spacing was the only concern. If not, can you be a bit more specific? Thanks!

**Comment by morloderex** [comment]
This is a potential breaking change.. For people using PHP lower than 7.0..

**Comment by vmitchell85** [comment]
Good point @morloderex I shouldn't have used the short ?? syntax. I can submit a new PR with the change.

**Comment by morloderex** [comment]
Please do 👍

**Comment by vmitchell85** [comment]
@morloderex - Submitted PR #700

**Pull request merged**
