### PR TITLE
spark:update should work on windows with this.

### PR DESCRIPTION
**Pull request by nerdalertdk**

### CODE REVIEW

**Comment by themsaid** [comment]
So, my fix did the trick for you?

**Comment by nerdalertdk** [comment]
Well think i did, before your fix my paths had / and \ in them now they only have the OS correct one.

When i tried to update,  Git had weirdly locked my vendor/spark folder so the script stopped, but it i did get past the view update part

**Comment by nerdalertdk** [comment]
trying to upgrade to 2.0.6 with this pull installed
At last the folder path is correct

```
 [ErrorException]                                                                                                                                    
 rename(C:\Users\*\Kode\*\website\spark-new\laravel-spark-ba10141775f55802b3db9d367ee103cf22472d9b,C:\Users\*\Kode\ 
 *\website\vendor\laravel\spark): Access is denied. (code: 5)                                                                               
```

**Comment by nerdalertdk** [comment]
Did some more testing, (turned gitcache off) its working :dancers: 

```
λ php artisan spark:update                    
Updating Views: Ô£ö                           
Updating Spark Directory: Ô£ö                 
Removing Temporary Download Directory: Ô£ö    
You are now running on Spark v2.0.6. Enjoy!   
```

**Comment by taylorotwell** [comment]
So is this no longer necessary?

**Pull request merged**
