### PR TITLE
[WIP] Integrate passport into spark

### PR DESCRIPTION
**Pull request by RSchwan**
This is my initial draft for integrating passport into spark. Fixes #218 .
For now I just integrated passport. I didn't remove the spark auth logic yet because I don't really know if I'll break something.
Another thing is the migration from existing spark applications. I'm not sure how easy it is going to be to migrate all the existing personal tokens (spark) to passport.

### CODE REVIEW

**Comment by RSchwan** [comment]
I'm trying to get the feature working if your session expired that you get this nice redirect to login modal.
The problem is passport requires the `X-CSRF-TOKEN` header to work. If your session expires your csrf token expires to (not sure). So without valid csrf token you get an 500 error (internal spark requests use  the web middleware so you get an TokenMismatchException) and therefore the modal doesn't work because it expected an 401 error. If I use the `X-XSRF-TOKEN` the modal works for spark internal requests but not for passport api requests because it [requires](https://github.com/laravel/passport/blob/master/src/Guards/TokenGuard.php#L166) the `X-CSRF-TOKEN` header.
I think the proper way properly would be to allow passport to accept the xsrf token as an alternative option to the csrf token. This way the `VerifyCsrfToken` middleware doesn't kick in and you don't get an 500 error.
I'm not even sure if all my arguments are valid. 😁
So what do you think?

**Comment by RSchwan** [comment]
I made a PR regarding the `X-XSRF-TOKEN` (see laravel/passport#79).

**Comment by taylorotwell** [comment]
We will look into doing this more officially.

**Comment by RSchwan** [comment]
For when is this planned? I want to use passport for my own projects and it would make sense for spark to have it directly integrated.

**Comment by themsaid** [comment]
@RSchwan we have this added to our features requests list and we'll be tackling it in a future release. No ETA for this, sorry :)

**Pull request closed without merging**
