### PR TITLE
Do not create a notification about the trial if it was not started for the team

### PR DESCRIPTION
**Pull request by piotrmocko**
The same fix as in https://github.com/laravel/spark/blob/3.0/src/Listeners/Subscription/CreateTrialEndingNotification.php#L37

### CODE REVIEW

**Comment by taylorotwell** [comment]
We never use "or", we always use "||".

**Comment by taylorotwell** [comment]
@themsaid does this look ok?

**Comment by piotrmocko** [comment]
I have updated the code to match your standards

**Comment by themsaid** [comment]
Yes looks ok, same fix as https://github.com/laravel/spark/pull/159

**Pull request merged**
