### PR TITLE
registerForm Errors

### PR DESCRIPTION
**Pull request by kinnedev**
Small fix to get form validation errors from the response and set registerForm.errors to the response array.

### CODE REVIEW

**Comment by taylorotwell** [comment]
@themsaid can you confirm?

**Comment by themsaid** [comment]
Register form seems to work fine, what errors do you get @kinnedev?

screen shot 2017-05-05 at 12 03 35 am

**Comment by devcircus** [comment]
Can confirm working as expected with latest version

**Comment by kinnedev** [comment]
Hey Guys, 

Sorry I must of not been running on the latest version. I had to do this in a project I just completed, but could not replicate with a fresh build. Sorry again!

**Pull request closed without merging**
