### PR TITLE
Allow html in plan features modal

### PR DESCRIPTION
**Pull request by Prepager**

### CODE REVIEW

**Comment by taylorotwell** [comment]
You should use {!! !!} to allow HTML.

**Comment by Prepager** [comment]
This is for VueJS not Blade. https://vuejs.org/guide/syntax.html#Raw-HTML

**Comment by DanielDarrenJones** [comment]
Just a weight in, In my personal opinion it should be standard to not allow HTML output. this offers a more defensive approach.

It should be opt in for people who want to allow raw HTML outputting as they will need to ensure this is parsed safely.

EDIT: In this particular case it would be fine, as there is no data from an outside source, but I still feel this is something that should be changed on a case by case basis.

**Comment by trip-somers** [comment]
Wouldn't they be opting in just by including HTML in their features?

**Comment by DanielDarrenJones** [comment]
Yes, but by including this for all, it opens up the possibility of injection.

In the use case it would be fine, but what if the user extends the functionality to let a admin edit the features from an interface there is a good chance this will open up a potential vulnerability.

On things like security I believe the framework should always be opt out, take mass assignment for example.

Just my 0.02$, I could be over analysing.

**Comment by trip-somers** [comment]
Not trying to nitpick here, but your described scenario is an opt-out. Building such an interface explicitly opts the application out (weird phrase, sure, but sticking with it for context) of the standard framework. Since the framework pulls that information from the plans defined in the service provider by the developer, it seems to me that those values are explicitly trusted.

If you introduce a vulnerability to those values, as you describe, then you'd have to fix the vulnerability you created. I can understand how some people might not recognize that they are creating a vulnerability by creating such an interface, but should the framework itself be responsible for a random developer's poor practices?

I'm not convinced either way, but my feelings lean toward allowing HTML (partly because that was one ofthe first things I tried when I first downloaded Spark but have been too lazy to mess with since),

**Comment by DanielDarrenJones** [comment]
You make a really good argument, honestly in this case it could go either way.

I just felt that the implications of doing that should be brought up so they can at least be considered.

It is a trusted value as you stated, and wouldn't effect 99.99% of people in a negative mannor.

**Comment by taylorotwell** [comment]
it might be better to just export and customize the view if you want HTML there.

**Pull request closed without merging**
