### PR TITLE
Spark for laravel 5.3

### PR DESCRIPTION
**Pull request by themsaid**

### CODE REVIEW

**Comment by fwartner** [comment]
Could it be, that you forgot the notifications table? Right now, spark has a table called "notification" but laravel also provides a scaffolding for this.. (Same name)

**Comment by themsaid** [comment]
Yeah will be tackling the notifications part in a different PR, after making sure the current code works perfectly with 5.3

**Comment by fwartner** [comment]
Ah great! Would like to test your code.. Could you share it?

**Comment by deiucanta** [comment]
Nice PR - when will this be ready? I'm ready to use some of the new features in Laravel 5.3 but I'm stuck.

**Comment by themsaid** [comment]
Soon enough :) Still need to tackle some stuff.

**Comment by ellisio** [comment]
I noticed in here that you're still using the single PasswordController. Any plans to break it out based on the notes provided in the Laravel 5.3 Upgrade -> Authentication section?

I did this in a branch of my own for our project that we've been building on 5.3 for some time now and it was a little cumbersome to say the least >_<

**Comment by deiucanta** [comment]
Can I help with anything?

**Comment by ConquestMedia** [comment]
So,I guess Laravel Spark 2 will be having support for Laravel 5.3? is it?

**Comment by themsaid** [comment]
@ConquestMedia yup

**Pull request merged**
