### PR TITLE
Fix for table to improve responsiveness on mobile

### PR DESCRIPTION
**Pull request by bryanjamesmiller**
This fixes the following issue: https://github.com/laravel/spark/issues/830

### CODE REVIEW

**Review by themsaid — CHANGES_REQUESTED** [review]
Can you wrap the `<table>` tag inside a `<div class="table-responsive">` instead?

**Comment by bryanjamesmiller** [comment]
@themsaid Yeah, although it will necessitate a CSS change as well.  I can update it shortly.

**Comment by bryanjamesmiller** [comment]
@themsaid I updated the PR.  I didn't change any CSS, so you can decide if you'd like to remove the outer border of the table.

**Comment by taylorotwell** [comment]
What was the point of putting it inside the div instead of the table?

**Comment by themsaid** [comment]
@taylorotwell that's how you wrap a responsive table in Bootstrap 3: https://getbootstrap.com/docs/3.3/css/#tables-responsive

First he was adding the class to the outermost div, which contains other stuff not only the table, now the class is set properly.

**Pull request merged**
