### PR TITLE
Reset notifications key after sortBy('created_at')

### PR DESCRIPTION
**Pull request by ericcch**
This will resolve issue https://github.com/laravel/spark/issues/107

Where multiple personal notifications will not show in notification modal

### CODE REVIEW

**Comment by DanielDarrenJones** [comment]
For my knowledge, why is this issue fixed by this? 

When I tested on my system there was no issues with multiple notification showing without it, I get that its resetting the keys, but not sure why this is needed?

Thanks for fixing!

**Comment by ericcch** [comment]
I noticed if the keys weren't in the right order, it affects the return json format. For example:

Keys not in order
`"notifications":{"6":{"id":"806bb72a-f2fe-435f-a3c8-fd9a3a9bb8e0","user_id":1}}`

Keys in the right order (This is what notification.js is expecting)
`"notifications":[{"id":"806bb72a-f2fe-435f-a3c8-fd9a3a9bb8e0","user_id":1}]`

**Comment by DanielDarrenJones** [comment]
Its odd that the first is an object containing objects, while the second is an array of objects.

From my testing the notifications were always returned as an array, there must be some root cause to this, possibly php version causing differences?

But if that works, its perfect :)

**Comment by judgej** [comment]
It is the way `json_encode()` works. If the array keys are not ALL numeric, zero-indexed and contiguous, then it will return an object rather than an array:

``` php
php > echo json_encode(array('hello'));
["hello"]
php > echo json_encode(array(0 => 'hello'));
["hello"]
php > echo json_encode(array(6 => 'hello'));
{"6":"hello"}

php > echo json_encode([0 => 'hello', 1 => 'world']);
["hello","world"]
php > echo json_encode([0 => 'hello', 2 => 'world']);
{"0":"hello","2":"world"}

php > echo json_encode(array_values([0 => 'hello', 2 => 'world']));
["hello","world"]
```

Using `array_values()` is a one way to ensure this is the case for all array, if the values of the keys are not functionally important.

**Comment by DanielDarrenJones** [comment]
Thanks for the response, that was really helpful for my knowledge, always looking to learn where possible :)

**Pull request merged**
