### PR TITLE
Fixes ownedTeams count query

### PR DESCRIPTION
**Pull request by matt-croft**
Fixes the ownedTeams count in CreateTeam throwing an SQL error when using maxTeams on a user plan.

### CODE REVIEW

**Comment by themsaid** [comment]
@mattcroftuk what was the error thrown?

**Comment by matt-croft** [comment]
Its throwing a "QueryException in Connection.php line 761":

> SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: select count(*) as aggregate from `teams` inner join `team_users` on `teams`.`id` = `team_users`.`team_id` where `team_users`.`user_id` = 2 and `owner_id` = 2 order by `name` asc)

**Comment by themsaid** [comment]
@mattcroftuk  I assume you're using MySQL 5.5.5-10.1.14-MariaDB?

**Comment by matt-croft** [comment]
@themsaid I'm using 10.1.16-MariaDB installed via brew

**Comment by themsaid** [comment]
The query is not faulty, however there's a bug in MariaDB 10.1.14 and it looks like it's still there in 10.1.16.

This query is completely valid `select count(*) as aggregate from teams inner join team_users on teams.id = team_users.team_id where team_users.user_id = 2 and owner_id = 2 order by name asc`, the error is saying `Mixing of GROUP columns` while there's **no group**.

We've received several reports on the laravel repository on this matter and I suggest you disable strict mode for MariaDB until the issue is addressed.

**Comment by matt-croft** [comment]
@themsaid ah ok, i thought it was down to a 5.3 upgrade issue.

As the the trait CanJoinTeams also does the count without the brackets in the method "totalPotentialCollaborators"

**Comment by themsaid** [comment]
I guess that's because in `totalPotentialCollaborators()` we've already loaded the models while doing `$this->ownedTeams->sum()` so no harm in counting them, however in `validateMaximumTeamsNotExceeded()` there's no need to load the whole model instances just to count them.

**Comment by themsaid** [comment]
I'm closing this PR since it's actually not solving any issue :) You'll still face a lot of these errors while on strict mode for MariaDB, so it's better that you disable strict mode.

**Pull request closed without merging**
