### PR TITLE
Update settings.blade.php

### PR DESCRIPTION
**Pull request by Braunson**
Checking that a user has at least one team before displaying the 'teams' tab and tab contents

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm not sure it's totally necessary to hide these tabs when they don't have teams?

**Comment by Braunson** [comment]
If they don't have any teams, it's a tab that does nothing when you click it, I figured for UI sake it would make more sense to hide it since no Teams exist and the tab does absolutely nothing.

**Comment by themsaid** [comment]
@Braunson I believe that we can't easily make such changes now that thousands of apps are running on Spark already and such changes might be considered breaking, the tab will disappear and will cause confusion.

**Comment by Braunson** [comment]
@themsaid I understand. 😃

**Pull request closed without merging**
