### PR TITLE
Don't show user subscribe if only team subscriptions

### PR DESCRIPTION
**Pull request by appix-CH**
#494

### CODE REVIEW

**Comment by taylorotwell** [comment]
@themsaid is this correct?

**Comment by themsaid** [comment]
@appix-CH if only team plans are available the user won't be on trial, so the condition won't display the enclosed markup.

**Comment by taylorotwell** [comment]
Can you provide your SparkServiceProvider so we can try to recreate?

**Comment by appix-CH** [comment]
It's possible the problem comes from the fact that I started without teams and team billing but added them later manually (not sure if I did it correctly, see #493)

I just did a `migrate:refresh` and tested it again (registered and selected basic plan), it still shows up.

Here's the `booted` method of my SparkServiceProvider:


```
Spark::noAdditionalTeams();
Spark::hideTeamSwitcher();

Spark::useStripe()->noCardUpFront()->trialDays(10);

Spark::freeTeamPlan()
    ->features([
        'First', 'Second', 'Third'
    ]);

Spark::teamPlan('Basic', 'publishing-basic')
    ->price(10)
    ->features([
        'First', 'Second', 'Third'
    ]);
```

While debugging I found that `$subscription`  in `cashier/src/Billable.php:151` is the team subscription.

**Comment by appix-CH** [comment]
Apparently `onGenericTrial()` (and therefore `onTrial()`) returns `true`, because the user has the `trial_ends_at` field set. But I haven't yet figured out why.

**Comment by appix-CH** [comment]
@taylorotwell  @themsaid  I found the problem: I didn't replace `trialDays(10)` with `teamTrialDays(10)`.  After I changed that everything works as it should. So this pull request is indeed unnecessary.

But I discovered that new users still have a `trial_ends_at` value with the current date and time because of this code in `Laravel\Spark\Repositories\UserRepository@create`:

```
    public function create(array $data)
    {
        $user = Spark::user();

        $user->forceFill([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
            'last_read_announcements_at' => Carbon::now(),
            'trial_ends_at' => Carbon::now()->addDays(Spark::trialDays()),
        ])->save();

        return $user;
    }
```

I suspect that's not expected behaviour, is it?

**Comment by taylorotwell** [comment]
Glad you got it fixed. @themsaid what do you think about their last comment?

**Comment by themsaid** [comment]
@taylorotwell  It has no effect if team billing is used afaik, so we can keep it as is with no harm or we can check if the trial days are zero we just save `null` instead.

**Pull request closed without merging**
