### PR TITLE
SendSupportEmail: Add "from" to message

### PR DESCRIPTION
**Pull request by vyuldashev**
For now, mail client shows "No Sender". Adding email to "From" would be helpful.

### CODE REVIEW

**Comment by taylorotwell** [comment]
You need to configure your "from" address in config/mail.php.

**Comment by vyuldashev** [comment]
@taylorotwell I mean "From" address will be the one user entered in support form.

**Comment by QWp6t** [comment]
As I understand it, this makes it so that if a user contacts support, the support inbox will display the email as being from the user (e.g., johndoe@gmail.com), as opposed to being from the system (e.g., noreply@example.com).

If that's the case, then this is a no-brainer. It should be accepted, or at least reconsidered.

**Comment by taylorotwell** [comment]
That's not going to be that great either. E-mail systems won't let you just send e-mails as whoever you want. Some will flag as SPAM and some won't accept them at all.

**Comment by gavinhoward100** [comment]
@vladimir-yuldashev The user's email is supplied in the Reply-To. Email services such as Sparkpost require the from address to be pre-verified or from a sending domain.

**Comment by vyuldashev** [comment]
I got the point. Thanks.

**Pull request closed without merging**
