### PR TITLE
Upgrade to Vue 2.0

### PR DESCRIPTION
**Pull request by themsaid**

### CODE REVIEW

**Comment by DanielDarrenJones** [comment]
Just a few small changes had to be made then....

Good work! 👍

**Comment by ellisio** [comment]
Redacted my comment, will update with ones that are actually VueJS 2.0 related and not stuff sitting around random non-Vue templates.

**Comment by ellisio** [comment]
```
1. Replace ready with mounted, then use Vue.nextTick if you need an in-document guarantee
  Line 4: install-stubs/resources/assets/js/components/home.js
  Reason: ready lifecycle hook has been deprecated
  More info: http://vuejs.org/guide/migration.html#ready-deprecated

14. Refactor lazy to a v-model modifier: v-model.lazy="registerForm.address"
  Line 6: resources/views/auth/register-address.blade.php
  Reason: v-model attribute params have been removed in favor of simpler modifier syntax
  More info: http://vuejs.org/guide/migration.html#v-model-with-lazy-or-number-Param-Attributes-deprecated

15. Refactor lazy to a v-model modifier: v-model.lazy="registerForm.address_line_2"
  Line 19: resources/views/auth/register-address.blade.php
  Reason: v-model attribute params have been removed in favor of simpler modifier syntax
  More info: http://vuejs.org/guide/migration.html#v-model-with-lazy-or-number-Param-Attributes-deprecated

16. Refactor lazy to a v-model modifier: v-model.lazy="registerForm.city"
  Line 32: resources/views/auth/register-address.blade.php
  Reason: v-model attribute params have been removed in favor of simpler modifier syntax
  More info: http://vuejs.org/guide/migration.html#v-model-with-lazy-or-number-Param-Attributes-deprecated

17. Refactor lazy to a v-model modifier: v-model.lazy="registerForm.state"
  Line 46: resources/views/auth/register-address.blade.php
  Reason: v-model attribute params have been removed in favor of simpler modifier syntax
  More info: http://vuejs.org/guide/migration.html#v-model-with-lazy-or-number-Param-Attributes-deprecated

18. Refactor lazy to a v-model modifier: v-model.lazy="registerForm.zip"
  Line 55: resources/views/auth/register-address.blade.php
  Reason: v-model attribute params have been removed in favor of simpler modifier syntax
  More info: http://vuejs.org/guide/migration.html#v-model-with-lazy-or-number-Param-Attributes-deprecated

19. Refactor lazy to a v-model modifier: v-model.lazy="registerForm.country"
  Line 68: resources/views/auth/register-address.blade.php
  Reason: v-model attribute params have been removed in favor of simpler modifier syntax
  More info: http://vuejs.org/guide/migration.html#v-model-with-lazy-or-number-Param-Attributes-deprecated
```

**Comment by themsaid** [comment]
@ellisio thank you, I think I need to look more into that.

**Comment by themsaid** [comment]
Updated the PR with using `v-model.lazy` instead of the `lazy` attribute.

**Comment by masonfox** [comment]
Do we have an estimate on when this will be merged? Much appreciated! Excited for this one! :+1:

**Comment by tobyryuk** [comment]
Is there a reason for not merging this yet? Don't mean to stress, just excited as well!

**Comment by dpde** [comment]
When will this change be available via `php artisan spark:update` ?

**Pull request merged**
