### PR TITLE
SparkForm display error message only one character

### PR DESCRIPTION
**Pull request by dinhquochan**
When submit to `/login` with wrong password. Server response:

```json
{
    "email": "These credentials do not match our records."
}
```

SpartForm display only:

```
T
```

Thank you.

### CODE REVIEW

**Comment by jmarcher** [comment]
I get the correct message on a fresh install

**Comment by taylorotwell** [comment]
@themsaid ?

**Comment by themsaid** [comment]
I have the right message printed as well, looks like you've made some adjustments to your Laravel Error handler where you return a string instead of an array?

**Comment by dinhquochan** [comment]
I found it:

```php

// Illuminate/Foundation/Auth/AuthenticatesUsers.php

    protected function sendFailedLoginResponse(Request $request)
    {
        $errors = [$this->username() => trans('auth.failed')];

        if ($request->expectsJson()) {
            return response()->json($errors, 422);
        }

        return redirect()->back()
            ->withInput($request->only($this->username(), 'remember'))
            ->withErrors($errors);
    }
```

It should be (if don't fix in SparkForm): 

```php
$errors = [$this->username() => [trans('auth.failed')]];
```

Because, validation reponses error:

```json
{
    "attribute": [
        "Error message 1",
        "Error message 2",
        "Error message 3",
        ...
    ]
}
```

**Comment by taylorotwell** [comment]
So is it a problem in Spark or not?

**Comment by themsaid** [comment]
@taylorotwell no I don't think it is something in Spark.

**Comment by dinhquochan** [comment]
Well, I think it should be fix in Laravel 👍  Thank you @taylorotwell  @themsaid

**Pull request closed without merging**
