### PR TITLE
team model fix

### PR DESCRIPTION
**Pull request by Jmrich**
Added team_id to Team relationships so that things work out the box if
a model other than Team is used

### CODE REVIEW

**Comment by taylorotwell** [comment]
The change to Billable doesn't appear correct to me. You can override these methods in your own code as needed.

**Comment by Jmrich** [comment]
I do have them overridden currently, but when I was initially setting it up I kept getting errors because the standard convention is looking for the model name, for example `Company`, and _id(`company_id`). All of the spark migrations have `team_id` columns since `Team` is the default model. By specifying `team_id` as the column we can change the team model without have to change any of the source code or overriding the methods. The change for `Billable` is necessary if a model other than `Team` is being used.

```
Column not found: 1054 Unknown column 'invoices.hospital_id' in 'where clause' (SQL: select * from `invoices` where `invoices`.`hospital_id` = 1 and `invoices`.`hospital_id` is not null order by `id` desc)
```

If we specify the column as `team_id`, which I do in the overridden methods, this can be avoided. It shouldn't be a breaking change because it looks for `team_id` by default. Not expecting a change but just wanted to let you know why I submitted the pr. Thought it would be helpful for someone else coming along in the future. I think it should be added to the documents which methods should be overridden at least

**Comment by huntercarter** [comment]
Thank you for this, @Jmrich.  Just ran into this issue using team billing with a non-standard team model name.  It looks like your PR hasn't been merged into Spark yet. What's the best way to implement this change until that happens? Manually change these two functions in spark's source? Or can these methods be overridden with spark's 'swap' method? And if so, what does that look like?

**Comment by huntercarter** [comment]
Perhaps something like this in `SparkServiceProvider.php`?

```
       // Override the billable trait to use team_id column
        Spark::swap('Billable@localInvoices', function ()
        {
            return $this->hasMany(LocalInvoice::class, 'team_id')->orderBy('id', 'desc');
        });

        // Override the team invitatinos method to use team_id column
        Spark::swap('Team@subscriptions', function ()
        {
            return $this->hasMany(Invitation::class, 'team_id');
        });

        // Override the team subscriptions method to use team_id column
        Spark::swap('Team@subscriptions', function ()
        {
            return $this->hasMany(TeamSubscription::class, 'team_id')->orderBy('created_at', 'desc');
        });
```

**Pull request closed without merging**
