### PR TITLE
Prepare spark for Localization - JSON

### PR DESCRIPTION
**Pull request by Prepager**
I have seen quite a lot of requests and have myself ended up with the need for translating Spark. So why not get started. I have not been able to test all the pages because of the many use cases. So help with that would be appreciated!

**~~The following issue needs to be resolved before this can be merged:~~** https://github.com/laravel/framework/issues/17923
^^ Not technically required for this specific pull request but is required if people want to extend Spark with new languages in this package.

- [X] Auth Views
- [x] Kiosk Views
- [x] Layouts Views
- [x] Modals Views
- [x] Nav Views
- [x] Settings Views
- [x] Shared Views
- [x] Root Views

### CODE REVIEW

**Comment by Prepager** [comment]
@taylorotwell Is this the correct method?

**Comment by taylorotwell** [comment]
@themsaid can review it more. I don't think you even need the en.json language file since it's the default language.

**Comment by Prepager** [comment]
@taylorotwell It's not required but it does make it a lot easier for people to translate it when they have a complete language file ready. I could make it into a template file if you want to? So there is only the English part on the left side in the JSON and the right side is just blank.

**Comment by taylorotwell** [comment]
I'm going to close this for now until the next major release because it will be a bigger work to do this for now. We will have to localize all English in the JavaScript as well as any English strings in the repositories, etc. I will revisit this when the time comes.

**Comment by Prepager** [comment]
@taylorotwell Would you merge this anytime soon if I included JavaScript translations in this pull request too?

**Comment by blomdahldaniel** [comment]
Would really appreciate if localisation was added for the future!

**Comment by timmoh** [comment]
What about this commit??? is there a timeline when the localization will be available? perhaps we can start with the view like above... @taylorotwell @themsaid

**Comment by cord** [comment]
Same question here!

**Pull request closed without merging**
